"""Second migration

Revision ID: 47b5361b03c6
Revises: 7c65ee96f581
Create Date: 2024-07-16 17:12:13.592733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b5361b03c6'
down_revision = '7c65ee96f581'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemons', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemons', 'type')
    # ### end Alembic commands ###
