"""Initial migration

Revision ID: 7c65ee96f581
Revises: 
Create Date: 2024-07-16 17:05:39.547042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c65ee96f581'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('base_experience', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('location_area_encounters', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('back_image', sa.String(), nullable=True),
    sa.Column('front_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemons_id'), 'pokemons', ['id'], unique=False)
    op.create_index(op.f('ix_pokemons_name'), 'pokemons', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemons_name'), table_name='pokemons')
    op.drop_index(op.f('ix_pokemons_id'), table_name='pokemons')
    op.drop_table('pokemons')
    # ### end Alembic commands ###
